export interface AudioTrackItem {
  id: string;
  title: string;
  artist: string;
  category: "indian" | "pakistani" | "sufi" | "classical" | "universal";
  categoryLabel: string;
  flag: string;
  tag?: string;
  duration: string;
  url: string;
  description: string;
}

export const CURATED_AUDIO_TRACKS: AudioTrackItem[] = [
  // ── 🇮🇳 TRENDING INDIAN WEDDING ──
  {
    id: "din-shagna-da",
    title: "Din Shagna Da",
    artist: "Jasleen Royal (Bridal Walk)",
    category: "indian",
    categoryLabel: "Trending Indian",
    flag: "🇮🇳",
    tag: "Most Popular Bridal",
    duration: "3:42",
    url: "/audio/din-shagna-da.mp3",
    description: "The quintessential Indian bridal entry anthem with soulful acoustic melodies.",
  },
  {
    id: "kudmayi-royale",
    title: "Kudmayi (Wedding Version)",
    artist: "Rocky Aur Rani / Pritam",
    category: "indian",
    categoryLabel: "Trending Indian",
    flag: "🇮🇳",
    tag: "Trending 2026",
    duration: "4:15",
    url: "/audio/kudmayi-royale.mp3",
    description: "Grand royal Punjabi wedding celebration with traditional dhol & shehnai fusion.",
  },
  {
    id: "ranjha-acoustic",
    title: "Ranjha (Sid-Kiara Wedding Cut)",
    artist: "B Praak & Jasleen Royal",
    category: "indian",
    categoryLabel: "Trending Indian",
    flag: "🇮🇳",
    tag: "Celebrity Favorite",
    duration: "3:50",
    url: "/audio/ranjha-acoustic.mp3",
    description: "Magical acoustic guitar and flute orchestration from the royal Jaisalmer wedding.",
  },
  {
    id: "madhanya-violin",
    title: "Madhanya (Bidaai Strings)",
    artist: "Rahul Vaidya & Asees Kaur",
    category: "indian",
    categoryLabel: "Trending Indian",
    flag: "🇮🇳",
    tag: "Emotional Classic",
    duration: "4:05",
    url: "/audio/madhanya-violin.mp3",
    description: "Heartwarming folk melody with soft emotional violin and acoustic harp.",
  },
  {
    id: "kesariya-sitar",
    title: "Kesariya (Acoustic Sitar & Sarod)",
    artist: "Arijit Singh / Acoustic Ensemble",
    category: "indian",
    categoryLabel: "Trending Indian",
    flag: "🇮🇳",
    tag: "Romantic Modern",
    duration: "3:30",
    url: "/audio/kesariya-sitar.mp3",
    description: "Sweet romantic sitar harmony blended with modern rhythm for royal entries.",
  },
  {
    id: "mangalyam-shehnai",
    title: "Mangalyam & Shehnai Royale",
    artist: "Vedic Royal Ensemble",
    category: "classical",
    categoryLabel: "Vedic Classical",
    flag: "🕉️",
    tag: "Auspicious Muhurat",
    duration: "3:15",
    url: "/audio/mangalyam-shehnai.mp3",
    description: "Traditional auspicious shehnai, nadaswaram, and temple bells for Vedic rituals.",
  },

  // ── 🇵🇰 TRENDING PAKISTANI WEDDING & COKE STUDIO ──
  {
    id: "pasoori-acoustic",
    title: "Pasoori (Acoustic Rubab & Strings)",
    artist: "Ali Sethi & Shae Gill (Coke Studio)",
    category: "pakistani",
    categoryLabel: "Trending Pakistani",
    flag: "🇵🇰",
    tag: "Global Sensation",
    duration: "3:44",
    url: "/audio/pasoori-acoustic.mp3",
    description: "Infectious Sufi folk rhythm with traditional Afghan rubab and acoustic bass.",
  },
  {
    id: "tu-jhoom-sufi",
    title: "Tu Jhoom (Soulful Sufi Santoor)",
    artist: "Abida Parveen & Naseebo Lal",
    category: "pakistani",
    categoryLabel: "Trending Pakistani",
    flag: "🇵🇰",
    tag: "Spiritual Masterpiece",
    duration: "4:50",
    url: "/audio/tu-jhoom-sufi.mp3",
    description: "Majestic spiritual trance with Kashmiri santoor, tabla, and soulful Sufi melodies.",
  },
  {
    id: "afreen-afreen",
    title: "Afreen Afreen (Royal Ghazal)",
    artist: "Rahat Fateh Ali Khan & Momina Mustehsan",
    category: "pakistani",
    categoryLabel: "Trending Pakistani",
    flag: "🇵🇰",
    tag: "Nikah Favorite",
    duration: "4:20",
    url: "/audio/afreen-afreen.mp3",
    description: "Evergreen romantic Sufi ghazal celebrating eternal beauty and royal charm.",
  },
  {
    id: "kahani-suno-piano",
    title: "Kahani Suno 2.0 (Piano & Cello)",
    artist: "Kaifi Khalil (Wedding Acoustic)",
    category: "pakistani",
    categoryLabel: "Trending Pakistani",
    flag: "🇵🇰",
    tag: "Soulful Ballad",
    duration: "3:25",
    url: "/audio/kahani-suno-piano.mp3",
    description: "Emotional, cinematic piano ballad that touches the heart of every guest.",
  },
  {
    id: "faasle-acoustic",
    title: "Faasle (Acoustic Guitar & Vocals)",
    artist: "Kaavish (Coke Studio Pakistan)",
    category: "pakistani",
    categoryLabel: "Trending Pakistani",
    flag: "🇵🇰",
    tag: "Aesthetic Indie",
    duration: "3:55",
    url: "/audio/faasle-acoustic.mp3",
    description: "Mellow, warm acoustic ballad with intricate harmonies and ambient guitar.",
  },

  // ── 🌙 SACRED NIKAH & SUFI QAWWALI ──
  {
    id: "kun-faya-kun-qawwali",
    title: "Kun Faya Kun (Sacred Nikah Harp)",
    artist: "A.R. Rahman / Sacred Symphony",
    category: "sufi",
    categoryLabel: "Sacred Nikah",
    flag: "🌙",
    tag: "Sacred Blessing",
    duration: "4:10",
    url: "/audio/kun-faya-kun-qawwali.mp3",
    description: "Ethereal Islamic spiritual harmony with silver harp, choir, and gentle ney flute.",
  },
  {
    id: "tajdar-e-haram",
    title: "Tajdar-e-Haram (Royal Rubab & Qawwali)",
    artist: "Atif Aslam / Sabri Tradition",
    category: "sufi",
    categoryLabel: "Sacred Nikah",
    flag: "🌙",
    tag: "Royal Mughal",
    duration: "4:35",
    url: "/audio/tajdar-e-haram.mp3",
    description: "Grand Mughal court ambiance with classical rubab, harmonium, and soft bells.",
  },

  // ── ✦ UNIVERSAL LUXURY & ORCHESTRAL ──
  {
    id: "wedding-ambience",
    title: "Grand Palace Orchestral Ambience",
    artist: "Royal Philharmonic Strings",
    category: "universal",
    categoryLabel: "Universal Royal",
    flag: "✦",
    tag: "Signature Royale",
    duration: "3:30",
    url: "/audio/wedding-ambience.mp3",
    description: "Rich cinematic strings, harpsichord, and palace ballroom acoustics.",
  },
];
